services:
  - type: web
    name: what2gift-api
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__Database
        fromDatabase:
          name: what2gift-db
          property: connectionString

databases:
  - name: what2gift-db
    plan: free
