services:
  - type: web
    name: what2gift-api
    env: dotnet
    plan: free
    region: singapore
    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o out
    startCommand: dotnet out/What2Gift.Apis.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__Database
        fromDatabase:
          name: what2gift-db
          property: connectionString

databases:
  - name: what2gift-db
    plan: free
